version: 2
updates:
- package-ecosystem: composer
  directory: "/plugin"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/plugin/vue"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
- package-ecosystem: poetry
  directory: "/microservice"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
